{{-- resources/views/patients/show.blade.php --}}
@extends('layouts.admission')

@section('content')

@if(session('success'))
<script>
    Swal.fire({
        icon: 'success',
        title: 'Success 🎉',
        html: `<b>{{ session('success') }}</b><br>
               Email: <code>{{ session('generatedEmail') }}</code><br>
               Password: <code>{{ session('plainPassword') }}</code>`,
        confirmButtonText: 'OK'
    });
</script>
@endif

@if(session('error'))
<script>
    Swal.fire({
        icon: 'error',
        title: 'Admission Failed ❌',
        text: '{{ session('error') }}',
        confirmButtonText: 'Try Again'
    });
</script>
@endif


<div class="container-fluid py-4">

  {{-- Flash autogenerated credentials (only right after creation) --}}
  @if(session('generatedEmail') && session('plainPassword'))
    <div class="alert alert-success">
      <p><strong>Credentials:</strong></p>
      <p>Email: <code>{{ session('generatedEmail') }}</code></p>
      <p>Password: <code>{{ session('plainPassword') }}</code></p>
    </div>
  @endif

  {{-- Page Header --}}
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h2 class="text-primary">
      Patient Details:
      {{ $patient->patient_first_name }} {{ $patient->patient_last_name }}
    </h2>
   <a href="{{ route('admission.patients.index') }}" class="btn btn-secondary">
      ← Back to Patients
    </a>
  </div>

  {{-- Personal Information --}}
  <div class="card mb-4">
    <div class="card-header">Personal Information</div>
    <div class="card-body">
      <p><strong>Email:</strong> {{ $patient->email }}</p>
      <p><strong>Password:</strong>
        @if(session('plainPassword'))
          <code>{{ session('plainPassword') }}</code>
        @else
          <span class="text-muted">••••••••</span>
        @endif
      </p>
      <p><strong>Phone:</strong> {{ $patient->phone_number ?? '—' }}</p>
      <p><strong>Birthday:</strong> {{ $patient->patient_birthday?->format('M d, Y') ?? '—' }}</p>
      <p><strong>Civil Status:</strong> {{ $patient->civil_status ?? '—' }}</p>
      <p><strong>Address:</strong> {{ $patient->address ?? '—' }}</p>
       <p><strong>Sex:</strong> {{ $patient->sex ?? '—' }}</p>
    </div>
  </div>

  {{-- Medical Details --}}
  <div class="card mb-4">
    <div class="card-header">Medical Details</div>
    <div class="card-body">
      <p><strong>Primary Reason:</strong> {{ $patient->medicalDetail?->primary_reason ?? '—' }}</p>
      <p><strong>Vitals:</strong>
        Weight {{ $patient->medicalDetail?->weight ?? '—' }} kg,
        Height {{ $patient->medicalDetail?->height ?? '—' }} cm,
        Temp {{ $patient->medicalDetail?->temperature ?? '—' }}°F,
        BP {{ $patient->medicalDetail?->blood_pressure ?? '—' }},
        HR {{ $patient->medicalDetail?->heart_rate ?? '—' }} bpm
      </p>

      @php
       $history = $patient->medicalDetail?->medical_history;
  if (is_string($history)) {
      $history = json_decode($history, true) ?: [];
  } elseif (! is_array($history)) {
      $history = [];
  }

  $allergies = $patient->medicalDetail?->allergies;
  if (is_string($allergies)) {
      $allergies = json_decode($allergies, true) ?: [];
  } elseif (! is_array($allergies)) {
      $allergies = [];
  }
      @endphp

      <p><strong>Medical History:</strong></p>
      @if(empty($history) || (collect($history)->filter(fn($v,$k)=>$k!=='others' && $v)->isEmpty() && empty($history['others'])))
        <p>—</p>
      @else
        <ul>
          @foreach($history as $key => $value)
            @continue($key === 'others' || !$value)
            <li>{{ ucwords(str_replace('_',' ',$key)) }}</li>
          @endforeach
          @if(!empty($history['others']))
            <li>Other: {{ $history['others'] }}</li>
          @endif
        </ul>
      @endif

      <p><strong>Allergies:</strong></p>
      @if(empty($allergies) || (collect($allergies)->filter(fn($v,$k)=>$k!=='others' && $v)->isEmpty() && empty($allergies['others'])))
        <p>—</p>
      @else
        <ul>
          @foreach($allergies as $key => $value)
            @continue($key === 'others' || !$value)
            <li>
              {{ $key==='none'
                 ? 'No Known Allergies'
                 : ucwords(str_replace('_',' ',$key))
              }}
            </li>
          @endforeach
          @if(!empty($allergies['others']))
            <li>Other: {{ $allergies['others'] }}</li>
          @endif
        </ul>
      @endif
    </div>
  </div>

  {{-- Admission Details --}}
  <div class="card mb-4">
    <div class="card-header">Admission Details</div>
    <div class="card-body">
      <p><strong>Date:</strong> {{ $patient->admissionDetail?->admission_date?->format('M d, Y') ?? '—' }}</p>
      <p><strong>Type:</strong> {{ $patient->admissionDetail?->admission_type ?? '—' }}</p>
      <p><strong>Source:</strong> {{ $patient->admissionDetail?->admission_source ?? '—' }}</p>
      <p><strong>Department:</strong> {{ $patient->admissionDetail?->department?->department_name ?? '—' }}</p>
      <p><strong>Doctor:</strong> {{ $patient->admissionDetail?->doctor?->doctor_name ?? '—' }}</p>
      <p><strong>Room/Bed:</strong>
         {{ $patient->admissionDetail?->room_number ?? '—' }} /
         {{ $patient->admissionDetail?->bed_number ?? '—' }}
      </p>
      <p><strong>Notes:</strong> {{ $patient->admissionDetail?->admission_notes ?? '—' }}</p>
    </div>
  </div>

  {{-- Billing Information --}}
  <div class="card mb-4">
    <div class="card-header">Billing Information</div>
    <div class="card-body">

      <p><strong>Guarantor Name:</strong> {{ $patient->billingInformation?->guarantor_name ?? '—' }}</p>
      <p><strong>Guarantor Relationship:</strong> {{ $patient->billingInformation?->guarantor_relationship ?? '—' }}</p>
      <hr>
    </div>
  </div>
</div>
@endsection
